### ISSUE TITLE
can-stache-binding's `enter` event should be implemented and documented here

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-util#213]
The code: https://github.com/canjs/can-stache-bindings/blob/master/can-stache-bindings.js#L982

should be removed and a `can-util/dom/events/enter/` module should be created instead.

**Comment by justinbmeyer** [comment]
Can be implemented similar to: https://github.com/canjs/can-util/blob/master/dom/events/attributes/attributes.js#L32

**Comment by andrejewski** [comment]
Wow, such change since this issue. To summarize, the enter event now lives in [`can-event-dom-enter`](https://github.com/canjs/can-event-dom-enter) which is exposed by `can-util/dom/events/enter` (which will be removed in v4.0.0). `can-stache-bindings` also uses this new package. The event is documented in its own repo and this issue can be closed.
