### ISSUE TITLE
Why obj == obj.window BUT NOT 'eqeqeq'

### ISSUE THREAD

**Issue by afeiship** [canjs/can-util#443]
https://github.com/canjs/can-util/blob/c4831a0e4aa58710f421b3b5331a73dca8798df3/js/is-plain-object/is-plain-object.js#L10

**Comment by chasenlehara** [comment]
Hi @afeiship, I’m not sure I understand your question.

The `jshint eqeqeq:false` comment is to disable JSHint’s check for `===`, because `==` is needed for that line (thanks to IE8… can-util doesn’t support it anymore, so we could probably remove that comment and make the check `===`).

https://github.com/canjs/can-util/blob/c4831a0e4aa58710f421b3b5331a73dca8798df3/js/is-plain-object/is-plain-object.js#L8-L10

**Comment by afeiship** [comment]
@chasenlehara 
// In IE8 window.window !== window.window, so we allow == here
Thanks, that is my question. (For ie8)
